//netbeans 26
//vinicius Souza dias 2564599



import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import main.java.LivroExecption;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valuc
 */
public class FromCadLivro extends javax.swing.JFrame implements Menus{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromCadLivro.class.getName());

    private Autor editora;
    private Armazenamento armazen;
    private Colecionavel colecionavel;
    private Didatico ditatico;
    private Infantil infantil;
    
    private static FromCadLivro fromCadLivroUnic;
          
    //singleton
    private FromCadLivro() {
        initComponents();
        armazen = Armazenamento.geraArmazen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTituloPagina = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rtID = new javax.swing.JLabel();
        cxId = new javax.swing.JTextField();
        rtTirulo = new javax.swing.JLabel();
        cxTitulo = new javax.swing.JTextField();
        rtAutor = new javax.swing.JLabel();
        cxAutor = new javax.swing.JTextField();
        rtEditora = new javax.swing.JLabel();
        cxEditora = new javax.swing.JTextField();
        rtSecao = new javax.swing.JLabel();
        cxSecao = new javax.swing.JTextField();
        rtPrateleira = new javax.swing.JLabel();
        cxPrateleira = new javax.swing.JTextField();
        rtLinha = new javax.swing.JLabel();
        cxLinha = new javax.swing.JTextField();
        rtTipo = new javax.swing.JLabel();
        slTipo = new javax.swing.JComboBox<>();
        pnCampos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btLimpar = new javax.swing.JButton();
        btCadastar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTituloPagina.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rtTituloPagina.setText("Cadastrar Livro");

        rtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 50, 10));

        rtID.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtID.setText("ID");
        jPanel1.add(rtID);

        cxId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdActionPerformed(evt);
            }
        });
        jPanel1.add(cxId);

        rtTirulo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtTirulo.setText("Titulo");
        jPanel1.add(rtTirulo);

        cxTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxTitulo);

        rtAutor.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtAutor.setText("CPF Autor");
        jPanel1.add(rtAutor);

        cxAutor.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxAutor);

        rtEditora.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtEditora.setText("CNPJ Editora");
        jPanel1.add(rtEditora);

        cxEditora.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxEditora);

        rtSecao.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtSecao.setText("Seção ");
        jPanel1.add(rtSecao);

        cxSecao.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxSecao);

        rtPrateleira.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtPrateleira.setText("Prateleira");
        jPanel1.add(rtPrateleira);

        cxPrateleira.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxPrateleira);

        rtLinha.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtLinha.setText("Linha");
        jPanel1.add(rtLinha);

        cxLinha.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(cxLinha);

        rtTipo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtTipo.setText("Tipo");
        jPanel1.add(rtTipo);

        slTipo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        slTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Colecioanvel", "Didatico", "Infantil" }));
        slTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slTipoActionPerformed(evt);
            }
        });
        jPanel1.add(slTipo);

        pnCampos.setLayout(new java.awt.GridLayout(3, 2, 50, 10));

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCadastar.setText("Cadastrar");
        btCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btCadastar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btCadastar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(rtNome))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtTituloPagina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(rtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rtTituloPagina)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastarActionPerformed

    private void cxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        clear();
    }//GEN-LAST:event_btLimparActionPerformed

    private void slTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slTipoActionPerformed
        toggle();
    }//GEN-LAST:event_slTipoActionPerformed

    
    public void toggle(){
        pnCampos.removeAll();
        
        String tipo = (String) slTipo.getSelectedItem();
        
        switch (tipo) {
        case "Colecioanvel":
            colecionavel();
            
            break;
        case "Didatico":
            didatico();
            
            break;
        case "Infantil":
            infantil();
            
            break;
        }
        
        pnCampos.revalidate(); // redesenha o painel
        pnCampos.repaint();
    }
    
    public void colecionavel(){
        JLabel rtEspeEdit = new JLabel("Edição especial:");
        JTextField cxEspeEdit = new JTextField();

        JLabel rtAdicional = new JLabel("Adicional:");
        JTextField cxAdicional = new JTextField();

        JLabel rtNumerado = new JLabel("Numerado:");
        JCheckBox ckNumerado = new JCheckBox("Sim");

        pnCampos.add(rtEspeEdit);
        pnCampos.add(cxEspeEdit);

        pnCampos.add(rtAdicional);
        pnCampos.add(cxAdicional);

        pnCampos.add(rtNumerado);
        pnCampos.add(ckNumerado);
    }
    
    public void didatico(){
        JLabel rtNivel = new JLabel("Nível de Ensino:");
        JTextField cxNivel = new JTextField();

        JLabel rtMateria = new JLabel("Matéria:");
        JTextField cxMateria = new JTextField();

        JLabel rtComplexidade = new JLabel("Complexidade:");
        JTextField cxComplexidade = new JTextField();

        pnCampos.add(rtNivel);
        pnCampos.add(cxNivel);

        pnCampos.add(rtMateria);
        pnCampos.add(cxMateria);

        pnCampos.add(rtComplexidade);
        pnCampos.add(cxComplexidade);
    }
    
    public void infantil(){
        JLabel rtFaixaEtaria = new JLabel("Faixa Etária:");
        JTextField cxFaixaEtaria = new JTextField();

        JLabel rtMaterial = new JLabel("Material:");
        JTextField cxMaterial = new JTextField();

        JLabel rtInterativo = new JLabel("Interativo:");
        JCheckBox ckInterativo = new JCheckBox("Sim");

        pnCampos.add(rtFaixaEtaria);
        pnCampos.add(cxFaixaEtaria);

        pnCampos.add(rtMaterial);
        pnCampos.add(cxMaterial);

        pnCampos.add(rtInterativo);
        pnCampos.add(ckInterativo);
    }
    
    public void clear(){
        slTipo.setSelectedIndex(0);
        cxId.setText("");
        cxTitulo.setText("");
        cxAutor.setText("");
        cxEditora.setText("");
        cxLinha.setText("");
        cxPrateleira.setText("");
        cxSecao.setText("");
        
    }
    
    //polimorfismo por sobrescrita
    @Override
    public void cadastrar(){
        
        String tipo = (String) slTipo.getSelectedItem();
        
        switch (tipo) {
        case "Colecioanvel":
            cadColecionavel();
            
            break;
        case "Didatico":
            caDdidatico();
            
            break;
        case "Infantil":
            cadInfantil();
            
            break;
        default:
            JOptionPane.showMessageDialog(
                null,
                "Selecione um tipo de livro.",
                "Cadastro de livro",
                JOptionPane.ERROR_MESSAGE
            );
            break;
        }
    }
    
    public Livro cadLivro(){
        //polimorfismo por coesão 
        Livro livro = new Colecionavel();  
        int intTempo = -1;
        
        intTempo = getInt(cxId.getText(),rtID.getText());
        if(intTempo == -1) return null;
        livro.setId(intTempo);

        for(Colecionavel temp : armazen.getBdColecionavel()) {
            if(temp.getId() == livro.getId()) {
                JOptionPane.showMessageDialog(
                    null,
                    "ID já cadastrado, tente novamente.",
                    "Cadastro de livro",
                    JOptionPane.ERROR_MESSAGE
                );
                return null;
            }
        }
        
        try{
            livro.setTitulo(cxTitulo.getText());
            break;
        }catch (LivroExecption exp) {
            exp.menExecption();
        }

        try{
            //reflexividade
            livro.getLocalizacao().setSecao(cxSecao.getText());
            break;
        }catch(LivroExecption exp){
            exp.menExecption();
        }

        intTempo = getInt(cxPrateleira.getText(),rtPrateleira.getText());
        if(intTempo == -1)  return null;
        //reflexividade
        livro.getLocalizacao().setPrateleira(intTempo);

        intTempo = getInt(cxLinha.getText(),rtLinha.getText());
        if(intTempo == -1) return null;
        //reflexividade
        livro.getLocalizacao().setLinha(intTempo);


        Autor autor = armazen.getAutorByCpf(cxAutor.getText());
        if(autor == null) {
            JOptionPane(
                null,
                "Autor não encontrado.",
                "Cadastro de livro",
                JOptionPane.ERROR_MESSAGE
            );
            return null;
        }

        if(autor.getBloqueado()) {
            JOptionPane.showMessageDialog(
                null,
                "Autor bloqueado.",
                "Cadastro de livro",
                JOptionPane.ERROR_MESSAGE
            );
            return null;
        }
        livro.setAutor(autor);

        Editora editora = armazen.getEditoraByCnpj(cxEditora.getText());
        if(editora == null){
            JOptionPane(
                null,
                "Editora não encontrado.",
                "Cadastro de livro",
                JOptionPane.ERROR_MESSAGE
            );
            return null;
        }
    
        if(editora.getBloqueado){
            JOptionPane(
                null,
                "Editora bloqueada.",
                "Cadastro de livro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        livro.setEditora(editora);


        return livro;
    } 


    public void cadColecionavel(){
        colecionavel = new Colecionavel();
        JOptionPane.showMessageDialog(
            null,
            "Selecione o tipo de livro como Colecionavel.",
            "Cadastro de livro",
            JOptionPane.INFORMATION_MESSAGE
        );
        colecionavel.setLivroGenerico(cadLivro());

    }

    public void caDdidatico(){

    }

    public void cadInfantil(){

    }

    public int getInt(String campo, String label){
        try {
            int number = Integer.parseInt(campo.trim());
            
            if (number <= 0) {
                JOptionPane.showMessageDialog(
                    null,
                    "O "+label+" não pode ser menor ou igual a zero.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );
                return -1; 
            }

            return number; 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "O "+label+" deve ser um número inteiro.",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            return null; 
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromCadLivro().setVisible(true));
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JTextField cxAutor;
    private javax.swing.JTextField cxEditora;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxLinha;
    private javax.swing.JTextField cxPrateleira;
    private javax.swing.JTextField cxSecao;
    private javax.swing.JTextField cxTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnCampos;
    private javax.swing.JLabel rtAutor;
    private javax.swing.JLabel rtEditora;
    private javax.swing.JLabel rtID;
    private javax.swing.JLabel rtLinha;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtPrateleira;
    private javax.swing.JLabel rtSecao;
    private javax.swing.JLabel rtTipo;
    private javax.swing.JLabel rtTirulo;
    private javax.swing.JLabel rtTituloPagina;
    private javax.swing.JComboBox<String> slTipo;
    // End of variables declaration//GEN-END:variables
}
