//netbeans IDe 26
//Vinicius Souza dias 2564599





import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valuc
 */
public class FromAtuEditora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromAtuEditora.class.getName());

    private Editora editora;
    private Armazenamento armazen;
    
    private static FromAtuEditora fromAtuEditunic; 
    
    private FromAtuEditora() {
        initComponents();
        armazen = Armazenamento.geraArmazen();
    }
    
    //singleton
    public static FromAtuEditora gerFromAtuEditora(){
        if(fromAtuEditunic == null){
            fromAtuEditunic = new FromAtuEditora();
        }
        
        return fromAtuEditunic;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtCpnpj = new javax.swing.JLabel();
        cxCnpj = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        rtDisponivel = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        ckBloqueado = new javax.swing.JCheckBox();
        btBuscar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rtTitulo.setText("Atualizar Editora");

        rtCpnpj.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtCpnpj.setText("Digite o CNPJ:");

        cxCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCnpjActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtNome.setText("Nome: ");

        rtDisponivel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtDisponivel.setText("Disponivel:");

        ckBloqueado.setText("Bloqueado");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btBuscar)
                            .addGap(50, 50, 50)
                            .addComponent(btLimpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                            .addComponent(btAtualizar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtCpnpj)
                                .addComponent(rtNome)
                                .addComponent(rtDisponivel))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ckBloqueado)
                                .addComponent(cxCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(cxNome)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(rtTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpnpj)
                    .addComponent(cxCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDisponivel)
                    .addComponent(ckBloqueado))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(btAtualizar)
                    .addComponent(btLimpar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCnpjActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        getEditora();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atuEditora();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        clear();
    }//GEN-LAST:event_btLimparActionPerformed

    public void atuEditora(){
        editora = new Editora();
        
        try{
            editora.setCnpj(cxCnpj.getText());
        }catch(EditoraExecption e) {
 
            editora = e.corTinyCnpjExecption(editora);
        }
        
        for(Editora temp : armazen.getBdEditoras()) {
            if(temp.getCnpj().equals(editora.getCnpj())) {
                try{
                    temp.setNome(cxNome.getText());
                }catch(EditoraExecption e) {
         
                    temp = e.corTinyNameExecption(editora);
                }
                
                temp.setBloqueado(ckBloqueado.isSelected());
                JOptionPane.showMessageDialog(
                    null,
                    "Editora atualizada",
                    "Atualizar editora",
                    JOptionPane.INFORMATION_MESSAGE
                );
                FromConEditora.gerFromAtuEditora().listaEditora();
                clear();
                return;
            }
        }   
        
        JOptionPane.showMessageDialog(
            null,
            "CNPJ não encontrado",
            "Atualizar editora",
            JOptionPane.ERROR_MESSAGE
        );
    }
    
    public void getEditora(){
        String cnpj = cxCnpj.getText();
        boolean findBusca = true;
        
        
        for(Editora editora : armazen.getBdEditoras()) {
            if(editora.getCnpj().equals(cnpj)) {
                cxNome.setText(editora.getNome());
                ckBloqueado.setSelected(editora.getBloqueado());
                findBusca = false;
                break;                
            }
            System.gc();
        }
        
        if(findBusca) {
            JOptionPane.showMessageDialog(
                null,
                "CNPJ não encontrado",
                "Atualizar editora",
                JOptionPane.ERROR_MESSAGE
            );
        }else{
            cxCnpj.setEnabled(false);
        }
        
        
    }
    
    public void clear(){
        cxCnpj.setText("");
        cxNome.setText("");
        ckBloqueado.setSelected(false);
        cxCnpj.setEnabled(true);
        cxCnpj.requestFocus();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromAtuEditora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBox ckBloqueado;
    private javax.swing.JTextField cxCnpj;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtCpnpj;
    private javax.swing.JLabel rtDisponivel;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
