//netbeans IDe 26
//Vinicius Souza dias 2564599





import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valuc
 */
public class FromAtuAutor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromAtuEditora.class.getName());

    private Autor autor;
    private Armazenamento armazen;
    
    private static FromAtuAutor fromAtuAutorUnic; 
    
    private FromAtuAutor() {
        initComponents();
        armazen = Armazenamento.geraArmazen();
    }
    
    //singleton
    public static FromAtuAutor gerFromAtuAutor(){
        if(fromAtuAutorUnic == null){
            fromAtuAutorUnic = new FromAtuAutor();
        }
        
        return fromAtuAutorUnic;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        cxCpf = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        rtDisponivel = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        ckBloqueado = new javax.swing.JCheckBox();
        btBuscar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rtTitulo.setText("Atualizar autor");

        rtCpf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtCpf.setText("Digite o CPF:");

        cxCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtNome.setText("Nome: ");

        rtDisponivel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rtDisponivel.setText("Disponivel:");

        cxNome.setEnabled(false);

        ckBloqueado.setText("Bloqueado");
        ckBloqueado.setEnabled(false);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btBuscar)
                            .addGap(50, 50, 50)
                            .addComponent(btLimpar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                            .addComponent(btAtualizar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtCpf)
                                .addComponent(rtNome)
                                .addComponent(rtDisponivel))
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ckBloqueado)
                                .addComponent(cxCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(cxNome)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(rtTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDisponivel)
                    .addComponent(ckBloqueado))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(btAtualizar)
                    .addComponent(btLimpar))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        getAutor();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atuAutor();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        clear();
    }//GEN-LAST:event_btLimparActionPerformed

    public void atuAutor(){
        autor = new Autor();
        
        try{
            autor.setCpf(cxCpf.getText());
        }catch(AutorExecption e) {
 
            autor = e.corTinyCpfExecption(autor);
        }
        
        autor = armazen.getAutorByCpf(autor.getCpf());

        if(autor == null) {
            JOptionPane.showMessageDialog(
                null,
                "Cpf não encontrado",
                "Atualizar autor",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try{
            autor.setNome(cxNome.getText());
        }catch(AutorExecption e) {
    
            autor = e.corTinyNameExecption(autor);
        }

        autor.setBloqueado(ckBloqueado.isSelected());
        JOptionPane.showMessageDialog(
            null,
            "Autor atualizada",
            "Atualizar autor",
            JOptionPane.INFORMATION_MESSAGE
        );
        FromConAutor.gerFromAtuAutor().listaAutor();
        FromPrincipal.gerarFromPrincipal().listarLivros();
        clear();
        return;
    }
    
    public void getAutor(){
        String cpf = cxCpf.getText();
        
        autor = armazen.getAutorByCpf(cpf);

        if(autor == null) {
            JOptionPane.showMessageDialog(
                null,
                "Cpf não encontrado",
                "Atualizar autor",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        cxCpf.setEnabled(false);
        cxNome.setEnabled(true);
        ckBloqueado.setEnabled(true);
        btAtualizar.setEnabled(true);
      
        cxNome.setText(autor.getNome());
        ckBloqueado.setSelected(autor.getBloqueado());
    }
    
    public void clear(){
        cxCpf.setText("");
        cxNome.setText("");
        cxCpf.setEnabled(true);
        cxNome.setEnabled(false);
        ckBloqueado.setEnabled(false);
        btAtualizar.setEnabled(false);
        ckBloqueado.setSelected(false);
        cxCpf.setEnabled(true);
        cxCpf.requestFocus();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromAtuAutor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBox ckBloqueado;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtDisponivel;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
