


//netbeans IDe 26
//Vinicius Souza dias 2564599









/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valuc
 */
public class FromPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromPrincipal.class.getName());
    
    
    /**
     * Creates new form Principal
     */
    public FromPrincipal() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnPrincipal = new javax.swing.JPanel();
        rtTitulo = new javax.swing.JLabel();
        cxBusca = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        rtBusca = new javax.swing.JLabel();
        rtMeioBusca = new javax.swing.JLabel();
        pnBusca = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        barMnPrincipal = new javax.swing.JMenuBar();
        mnLivro = new javax.swing.JMenu();
        mnColecionavel = new javax.swing.JMenu();
        itMnCadColecioanvel = new javax.swing.JMenuItem();
        itMnAtuColecionavel = new javax.swing.JMenuItem();
        mnDidatico = new javax.swing.JMenu();
        itMnCadDidatico = new javax.swing.JMenuItem();
        itMnAtuDidatico = new javax.swing.JMenuItem();
        mnInfantil = new javax.swing.JMenu();
        itMnCadInfantil = new javax.swing.JMenuItem();
        itMnAtuInfantil = new javax.swing.JMenuItem();
        mnEditora = new javax.swing.JMenu();
        itMnCadEditora = new javax.swing.JMenuItem();
        itMnAtuEditora = new javax.swing.JMenuItem();
        itMnConsultar = new javax.swing.JMenuItem();
        mnAutor = new javax.swing.JMenu();
        itMnCadAutor = new javax.swing.JMenuItem();
        itMnAtuAutor = new javax.swing.JMenuItem();
        itMnConsultar1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        rtTitulo.setText("Bem Vindo ");

        cxBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxBuscaActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        rtNome.setText("A Delkv");

        rtBusca.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rtBusca.setText("Busque um livro");

        rtMeioBusca.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        rtMeioBusca.setText("Digite o titulo, Autor ou Editora");

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtMeioBusca)
                    .addComponent(rtBusca)
                    .addComponent(cxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtNome)
                    .addComponent(rtTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(rtTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtNome)
                .addGap(41, 41, 41)
                .addComponent(rtBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtMeioBusca)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Autor", "Editora"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Clique em um livro para ver mais detalhes");

        javax.swing.GroupLayout pnBuscaLayout = new javax.swing.GroupLayout(pnBusca);
        pnBusca.setLayout(pnBuscaLayout);
        pnBuscaLayout.setHorizontalGroup(
            pnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuscaLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuscaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnBuscaLayout.setVerticalGroup(
            pnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
        );

        mnLivro.setText("Livro");

        mnColecionavel.setText("Colecionavel");

        itMnCadColecioanvel.setText("Cadastar...");
        mnColecionavel.add(itMnCadColecioanvel);

        itMnAtuColecionavel.setText("Atualizar...");
        itMnAtuColecionavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAtuColecionavelActionPerformed(evt);
            }
        });
        mnColecionavel.add(itMnAtuColecionavel);

        mnLivro.add(mnColecionavel);

        mnDidatico.setText("Didatico");

        itMnCadDidatico.setText("Cadastar...");
        mnDidatico.add(itMnCadDidatico);

        itMnAtuDidatico.setText("Atualizar...");
        mnDidatico.add(itMnAtuDidatico);

        mnLivro.add(mnDidatico);

        mnInfantil.setText("Infantil");

        itMnCadInfantil.setText("Cadastar...");
        mnInfantil.add(itMnCadInfantil);

        itMnAtuInfantil.setText("Atualizar...");
        mnInfantil.add(itMnAtuInfantil);

        mnLivro.add(mnInfantil);

        barMnPrincipal.add(mnLivro);

        mnEditora.setText("Editora");

        itMnCadEditora.setText("Cadastar...");
        itMnCadEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadEditoraActionPerformed(evt);
            }
        });
        mnEditora.add(itMnCadEditora);

        itMnAtuEditora.setText("Atualizar...");
        itMnAtuEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAtuEditoraActionPerformed(evt);
            }
        });
        mnEditora.add(itMnAtuEditora);

        itMnConsultar.setText("Consulta..");
        itMnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnConsultarActionPerformed(evt);
            }
        });
        mnEditora.add(itMnConsultar);

        barMnPrincipal.add(mnEditora);

        mnAutor.setText("Autor");

        itMnCadAutor.setText("Cadastrar...");
        itMnCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAutorActionPerformed(evt);
            }
        });
        mnAutor.add(itMnCadAutor);

        itMnAtuAutor.setText("Atualizar...");
        itMnAtuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAtuAutorActionPerformed(evt);
            }
        });
        mnAutor.add(itMnAtuAutor);

        itMnConsultar1.setText("Consulta..");
        itMnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnConsultar1ActionPerformed(evt);
            }
        });
        mnAutor.add(itMnConsultar1);

        barMnPrincipal.add(mnAutor);

        setJMenuBar(barMnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnAtuColecionavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAtuColecionavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itMnAtuColecionavelActionPerformed

    private void itMnAtuEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAtuEditoraActionPerformed
        FromAtuEditora.gerFromAtuEditora().setVisible(true);
    }//GEN-LAST:event_itMnAtuEditoraActionPerformed

    private void itMnCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAutorActionPerformed
       FromCadAutor.gerarFromCadAutor().setVisible(true);
    }//GEN-LAST:event_itMnCadAutorActionPerformed

    private void cxBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxBuscaActionPerformed

    private void itMnCadEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadEditoraActionPerformed
        FromCadEditora.gerarFromCadEditora().setVisible(true);
    }//GEN-LAST:event_itMnCadEditoraActionPerformed

    private void itMnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnConsultarActionPerformed
        FromConEditora.gerFromAtuEditora().setVisible(true);
    }//GEN-LAST:event_itMnConsultarActionPerformed

    private void itMnAtuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAtuAutorActionPerformed
        FromAtuAutor.gerFromAtuAutor().setVisible(true);
    }//GEN-LAST:event_itMnAtuAutorActionPerformed

    private void itMnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnConsultar1ActionPerformed
        FromConAutor.gerFromAtuAutor().setVisible(true);
    }//GEN-LAST:event_itMnConsultar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMnPrincipal;
    private javax.swing.JTextField cxBusca;
    private javax.swing.JMenuItem itMnAtuAutor;
    private javax.swing.JMenuItem itMnAtuColecionavel;
    private javax.swing.JMenuItem itMnAtuDidatico;
    private javax.swing.JMenuItem itMnAtuEditora;
    private javax.swing.JMenuItem itMnAtuInfantil;
    private javax.swing.JMenuItem itMnCadAutor;
    private javax.swing.JMenuItem itMnCadColecioanvel;
    private javax.swing.JMenuItem itMnCadDidatico;
    private javax.swing.JMenuItem itMnCadEditora;
    private javax.swing.JMenuItem itMnCadInfantil;
    private javax.swing.JMenuItem itMnConsultar;
    private javax.swing.JMenuItem itMnConsultar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenu mnAutor;
    private javax.swing.JMenu mnColecionavel;
    private javax.swing.JMenu mnDidatico;
    private javax.swing.JMenu mnEditora;
    private javax.swing.JMenu mnInfantil;
    private javax.swing.JMenu mnLivro;
    private javax.swing.JPanel pnBusca;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JLabel rtBusca;
    private javax.swing.JLabel rtMeioBusca;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
