/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valuc
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnPrincipal = new javax.swing.JPanel();
        rtTitulo = new javax.swing.JLabel();
        cxBuca = new javax.swing.JTextField();
        rtNome = new javax.swing.JLabel();
        rtBusca = new javax.swing.JLabel();
        pnBusca = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        barMnPrincipal = new javax.swing.JMenuBar();
        mnLivro = new javax.swing.JMenu();
        mnColecionavel = new javax.swing.JMenu();
        itMnCadColecioanvel = new javax.swing.JMenuItem();
        itMnDelColecionavel = new javax.swing.JMenuItem();
        itMnReaColecionavel = new javax.swing.JMenuItem();
        mnDidatico = new javax.swing.JMenu();
        itMnCadDidatico = new javax.swing.JMenuItem();
        itMnDelDidatico = new javax.swing.JMenuItem();
        itMnReaDidatico = new javax.swing.JMenuItem();
        mnInfantil = new javax.swing.JMenu();
        itMnCadInfantil = new javax.swing.JMenuItem();
        itMnDelInfantil = new javax.swing.JMenuItem();
        itMnReaInfantil = new javax.swing.JMenuItem();
        mnEditora = new javax.swing.JMenu();
        itMnDelEditora = new javax.swing.JMenuItem();
        itMnCadEditora = new javax.swing.JMenuItem();
        itMnReaEditora = new javax.swing.JMenuItem();
        mnAutor = new javax.swing.JMenu();
        itMnDelAutor = new javax.swing.JMenuItem();
        itMnCadColecioanvel2 = new javax.swing.JMenuItem();
        itMnReaColecionavel2 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        rtTitulo.setText("Bem Vindo ");

        cxBuca.setText("Titulo do livro");

        rtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        rtNome.setText("A Delkv");

        rtBusca.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        rtBusca.setText("Digite o titulo do livro buscado");

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtBusca)
                    .addComponent(cxBuca, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(rtTitulo)
                .addGap(30, 30, 30)
                .addComponent(rtNome)
                .addGap(29, 29, 29)
                .addComponent(rtBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxBuca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Autor", "Editora"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout pnBuscaLayout = new javax.swing.GroupLayout(pnBusca);
        pnBusca.setLayout(pnBuscaLayout);
        pnBuscaLayout.setHorizontalGroup(
            pnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscaLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnBuscaLayout.setVerticalGroup(
            pnBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );

        mnLivro.setText("Livro");

        mnColecionavel.setText("Colecionavel");

        itMnCadColecioanvel.setText("Cadastar...");
        mnColecionavel.add(itMnCadColecioanvel);

        itMnDelColecionavel.setText("Excluir...");
        itMnDelColecionavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnDelColecionavelActionPerformed(evt);
            }
        });
        mnColecionavel.add(itMnDelColecionavel);

        itMnReaColecionavel.setText("Reativar...");
        mnColecionavel.add(itMnReaColecionavel);

        mnLivro.add(mnColecionavel);

        mnDidatico.setText("Didatico");

        itMnCadDidatico.setText("Cadastar...");
        mnDidatico.add(itMnCadDidatico);

        itMnDelDidatico.setText("Excluir...");
        mnDidatico.add(itMnDelDidatico);

        itMnReaDidatico.setText("Reativar...");
        mnDidatico.add(itMnReaDidatico);

        mnLivro.add(mnDidatico);

        mnInfantil.setText("Infantil");

        itMnCadInfantil.setText("Cadastar...");
        mnInfantil.add(itMnCadInfantil);

        itMnDelInfantil.setText("Excluir...");
        mnInfantil.add(itMnDelInfantil);

        itMnReaInfantil.setText("Reativar...");
        mnInfantil.add(itMnReaInfantil);

        mnLivro.add(mnInfantil);

        barMnPrincipal.add(mnLivro);

        mnEditora.setText("Editora");

        itMnDelEditora.setText("Excluir...");
        itMnDelEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnDelEditoraActionPerformed(evt);
            }
        });
        mnEditora.add(itMnDelEditora);

        itMnCadEditora.setText("Cadastar...");
        mnEditora.add(itMnCadEditora);

        itMnReaEditora.setText("Reativar...");
        mnEditora.add(itMnReaEditora);

        barMnPrincipal.add(mnEditora);

        mnAutor.setText("Autor");

        itMnDelAutor.setText("Excluir...");
        itMnDelAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnDelAutorActionPerformed(evt);
            }
        });
        mnAutor.add(itMnDelAutor);

        itMnCadColecioanvel2.setText("Cadastar...");
        mnAutor.add(itMnCadColecioanvel2);

        itMnReaColecionavel2.setText("Reativar...");
        mnAutor.add(itMnReaColecionavel2);

        barMnPrincipal.add(mnAutor);

        setJMenuBar(barMnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnDelColecionavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnDelColecionavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itMnDelColecionavelActionPerformed

    private void itMnDelEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnDelEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itMnDelEditoraActionPerformed

    private void itMnDelAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnDelAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itMnDelAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMnPrincipal;
    private javax.swing.JTextField cxBuca;
    private javax.swing.JMenuItem itMnCadColecioanvel;
    private javax.swing.JMenuItem itMnCadColecioanvel2;
    private javax.swing.JMenuItem itMnCadDidatico;
    private javax.swing.JMenuItem itMnCadEditora;
    private javax.swing.JMenuItem itMnCadInfantil;
    private javax.swing.JMenuItem itMnDelAutor;
    private javax.swing.JMenuItem itMnDelColecionavel;
    private javax.swing.JMenuItem itMnDelDidatico;
    private javax.swing.JMenuItem itMnDelEditora;
    private javax.swing.JMenuItem itMnDelInfantil;
    private javax.swing.JMenuItem itMnReaColecionavel;
    private javax.swing.JMenuItem itMnReaColecionavel2;
    private javax.swing.JMenuItem itMnReaDidatico;
    private javax.swing.JMenuItem itMnReaEditora;
    private javax.swing.JMenuItem itMnReaInfantil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenu mnAutor;
    private javax.swing.JMenu mnColecionavel;
    private javax.swing.JMenu mnDidatico;
    private javax.swing.JMenu mnEditora;
    private javax.swing.JMenu mnInfantil;
    private javax.swing.JMenu mnLivro;
    private javax.swing.JPanel pnBusca;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JLabel rtBusca;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
